#!/bin/bash
DIR="$1"
shift 1
case "$DIR" in
	"" | ".")
		gcc -MM -MG "$@" | sed -e 's@^\(.*\)\.o:@.PRECIOUS \1.d \1.o:@'
		;;
	*)
		gcc -MM -MG "$@" | sed -e "s@^\(.*\)\.o:@.PRECIOUS $DIR/\1.d $DIR/\1.o:@"
		;;
esac
