#!/usr/bin/env Rscript

#Gathers a taxa-list in wide format from a CSV file into a tidy format.
#The output comes in three columns:
#site, variable, value

library(tidyverse)
library(magrittr)
library(optparse)

option_list <- list(
	make_option(c("-t", "--transpose"), type = "logical", action="store_true", default=FALSE, dest="transpose",
		help="Sites are in columns rather than rows"),
	make_option(c("-i", "--ignore"), type = "integer", action="store", default=0, dest="ignore_columns",
		help="Delete some number of columns after the first, before including the rest")
)
parser <- OptionParser(usage = "%prog [options] <taxa list CSV> <output file>", option_list=option_list)
arguments <- parse_args(parser, positional_arguments = 2)

input_file <- arguments$args[1]
output_file <- arguments$args[2]

transpose <- arguments$options$transpose
ignore_columns <- arguments$options$ignore_columns

data <- read_csv(input_file)

if(ignore_columns > 0) {
	data %<>% select(-2:-(1+ignore_columns))
}

if(!transpose) {
	names(data)[1] <- "site"
	data %<>%
		gather(key = "variable", value = "value", -1)
} else {
	names(data)[1] <- "variable"
	data %<>%
		gather(key = "site", value = "value", -1) %>%
		select("site", "variable", "value") #Ensure ordering
}

write_csv(data, output_file)
