#!/usr/bin/env Rscript

#Reads two csv files with two columns
#Both have the same set of sites in the first column
#One has a predictor variable in the second, the other a response

#Optionally plots the regression line
#Optionally gives a file with the r^2, F and p values, formatted for TeX.

set.seed(1)

library(tidyverse)
library(magrittr)
library(ggrepel)
library(optparse)

option_list <- list(
	make_option(c("-p", "--plotfile"), type = "character", action="store", default=FALSE, dest="plot_file",
		help="A PDF file to output the plot to"),
	make_option(c("-b", "--binomialfile"), type = "character", action="store", default=FALSE, dest="binomial_file",
		help="A CSV file with the totals of the response variable (require method binomial)"),
	make_option(c("-t", "--texfile"), type = "character", action="store", default=FALSE, dest="tex_file",
		help="A TeX file to output the statistics to"),
	make_option(c("-x", "--xlab"), type = "character", action="store", default="predictor", dest="x_label",
		help="The x-axis label for the graph [default: %default]"),
	make_option(c("-y", "--ylab"), type = "character", action="store", default="response", dest="y_label",
		help="The y-axis label for the graph [default: %default]"),
	make_option(c("-w", "--width"), type = "numeric", action="store", default="7", dest="plot_width",
		help="The width of the plot, in inches [default: %default]"),
	make_option(c("-v", "--height"), type = "numeric", action="store", default="7", dest="plot_height",
		help="The height of the plot, in inches [default: %default]")
)
parser <- OptionParser(usage = "%prog [options] <method> <response CSV> <predictor CSV>\n\tmethod is `gaussian`, `poisson`, `quasipoisson`, `binomial` or `quasibinomial`", option_list=option_list)
arguments <- parse_args(parser, positional_arguments = 3)

regression_method <- arguments$args[1]
response_file <- arguments$args[2]
predictor_file <- arguments$args[3]

plot_file <- arguments$options$plot_file
tex_file <- arguments$options$tex_file
binomial_file <- arguments$options$binomial_file
x_label <- arguments$options$x_label
y_label <- arguments$options$y_label
plot_width <- arguments$options$plot_width
plot_height <- arguments$options$plot_height

is_plot <- is.character(plot_file) && (plot_file != "FALSE")
is_tex <- is.character(tex_file) && (tex_file != "FALSE")
is_binomial_file <- is.character(binomial_file) && (binomial_file != "FALSE")
if(xor(is_binomial_file, (regression_method == "binomial" || regression_method == "quasibinomial"))) {
	cat("Binomial regression requires an extra CSV file, and vice versa.\n")
	parser.print_help()
	quit()
}

invalid_method <- function() {
	cat("Invalid regression method.\n")
	parser.print_help()
	quit()
}

response_data <- read_csv(response_file)
names(response_data) <- c("site", "response")
predictor_data <- read_csv(predictor_file)
names(predictor_data) <- c("site", "predictor")

data <- inner_join(response_data, predictor_data, by = "site")

if(is_binomial_file) {
	total_data <- read_csv(binomial_file)
	names(total_data) <- c("site", "total")
	data %<>%
		inner_join(total_data, by = "site") %>%
		mutate(success = response) %>%
		mutate(response = success / total, failure = total - success)
}

if(is_plot) {
	pdf(plot_file, width=plot_width, height=plot_height)
	plot_object <- ggplot(data) +
		aes(x=predictor, y=response, label=site) +
		expand_limits(y=0)
	
	if(regression_method == "gaussian") {
		plot_object <- plot_object +
			geom_smooth(method='lm')
	} else if(regression_method == "poisson" || regression_method == "quasipoisson") {
		plot_object <- plot_object +
			geom_smooth(
				method='glm',
				method.args = list(family = regression_method)
			)
	} else if(regression_method == "binomial" || regression_method == "quasibinomial") {
		plot_object <- plot_object +
			geom_smooth(
				method='glm',
				method.args = list(family = regression_method),
				aes(weight = total)
			)
	} else {
		invalid_method()
	}
	
	plot_object <- plot_object +
		geom_point() +
		geom_text_repel() +
		xlab(x_label) +
		ylab(y_label)
	plot(plot_object)
	dev.off()
}

p_stringify <- function(p_val) {
	p_val_string <- sprintf("p = %.3f", p_val)
	if(p_val_string == "p = 0.000") {
		p_val_string <- sprintf("p < 0.001")
	}
	return(p_val_string)
}

if(is_tex) {
	if(regression_method == "gaussian") {
		
		model <- lm(response~predictor, data=data)
		
		r2 <- summary(model)$r.squared
		numerator_df <- summary(model)$fstatistic['numdf']
		denominator_df <- summary(model)$fstatistic['dendf']
		f_val <- summary(model)$fstatistic['value']
		p_val <- summary(model)$coefficients[-1,4]
		
		out_string <- sprintf("$r^2 = %.3f$, $F_{%d,%d} = %.2f$, $%s$",
			r2, numerator_df, denominator_df, f_val, p_stringify(p_val))
		
	} else if(regression_method == "poisson" || regression_method == "quasipoisson") {
		
		model <- glm(response~predictor, data=data, family=regression_method)
		
		z_val <- summary(model)$coefficients[-1,3]
		p_val <- summary(model)$coefficients[-1,4]
		if(regression_method == "poisson") {
			dispersion_parameter <- summary(model)$deviance / summary(model)$df.residual
		} else if(regression_method == "quasipoisson") {
			dispersion_parameter <- summary(model)$dispersion
		}
		
		out_string <- sprintf("$z = %.2f$, $%s$, $\\text{dispersion parameter} = %.2f$",
			z_val, p_stringify(p_val), dispersion_parameter)
		
	} else if(regression_method == "binomial" || regression_method == "quasibinomial") {
		
		model <- glm(cbind(success,failure)~predictor, data=data, family=regression_method)
		
		print(summary(model)$coefficients)
		
		z_val <- summary(model)$coefficients[-1,3]
		p_val <- summary(model)$coefficients[-1,4]
		if(regression_method == "binomial") {
			dispersion_parameter <- summary(model)$deviance / summary(model)$df.residual
		} else if(regression_method == "quasibinomial") {
			dispersion_parameter <- summary(model)$dispersion
		}
		
		out_string <- sprintf("$z = %.2f$, $%s$, $\\text{dispersion parameter} = %.2f$",
			z_val, p_stringify(p_val), dispersion_parameter)
		
	} else {
		invalid_method()
	}
	
	
	
	file_connection <- file(tex_file)
	writeLines(out_string, file_connection)
	close(file_connection)
}
